### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by vachan-maker**

### CODE REVIEW

**Comment by tibbi** [comment]
nice, thanks

**Comment by vachan-maker** [comment]
I noticed that not all the strings have been translated. I can still some text in English. Is it meant to be that way?

**Comment by tibbi** [comment]
you can translate anything except lines starting with <!--, those are comments

**Comment by vachan-maker** [comment]
But what about text like 'Primary color', 'color'. i don't see them

**Comment by tibbi** [comment]
strings reused by multiple apps are stored in Simple Commons, it is at https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res . The link can be found at the bottom of every strings file.

**Comment by vachan-maker** [comment]
Ok. Thanks for the reply. 
Will translate that as well. Have a nice day. Also, thanks for making these simple apps

**Pull request merged**
