### PR TITLE
Update Russian

### PR DESCRIPTION
**Pull request by solokot**
Mainly GP description

### CODE REVIEW

**Comment by tibbi** [comment]
Nice, thanks. You can translate app names too (first string) when you will be doing some updates.

**Comment by solokot** [comment]
Hello!

In my opinion, it's better not to do this: "Simple ..." is like (tm),
recognizable and visually. For example
, "Simple Music Player" was translated as simply "Music Player", nonsense
turned out.

2018-01-10 18:38 GMT+03:00 Tibor Kaputa <notifications@github.com>:

**Comment by tibbi** [comment]
ye but people search in their own language, so I prefer translating it. I translated it in my language too, leaving it as it is isnt a big deal tho.

**Comment by trubitsyn** [comment]
Although I like "Simple ..." names more too, apps with translated names are still searchable.

**Pull request merged**
