### PR TITLE
Dev add complete androidcontact

### PR DESCRIPTION
**Pull request by rlieger**
I implemented the following changes:
.) All contact models now contain all the fields provided by Android ContactContract.
You previously only copied selected fields from the Android ContactContract to the internal Contact class and when writing back a modified contact those fields that were not part of the Contact class were deleted. I consider that very bad style, even if SimpleContact does not use these fields, other Contact management application or contact synchronisation tools might do so and simply deleting that information for no good reason seems bad to me.
.) The LocalContact has been expanded to match the Android ContactContract. Suitable converters from the previous data format have been added.
.) I also added comments to all contact classes explaining the connection to the Android ContactContract and the DAVCard format.
.) I added a structured address to the contact (in addition to the preformatted address), and implemented logic that will automatically update the preformatted address when the structured address changes (and the preformatted adresse was not previously modified by hand). The format of the preformatted address can be changed via localisation (but not yet be the target country of the address)
.) I added a formatted (full) name in addition to the structured name and implemented logic that automatically update the full name in a variety of (user selectable) formats.
.) I added phonetic names
.) I added support for multiple nicknames (optional - can be enabled/disabled in the Setting activity)
.) I added support for types of websites
.) I added support for types and protocols of instant messenger addresses (rather than abusing the type field to contain protocol information). I also added several modern IM applications to be predefined "custom" types.
.) I added support for relations (with support for the standard Android and vCard relation types as well as a wide range of custom types)
.) For item classes where multiple entries of one type are possible for one contact, you provide a '+' button to add additional items. Deleting unwanted items is usually accomplished by deleting the contents, but for events a '-' button is provided because the date can not be deleted. I added the option to provide a '-' button for all types of items, so that there is a consitency between creating items with a '+' button and deleting items with a '-' button. This feature can be enabled/disabled in the setting dialog (and is disabled by default).
.) When sharing a contact the user can (optionally) select which items of a contact shall be shared. Thus it is possible to store private/sensitive information in a contact and still share (the public part of) it.
.) When storing a contact back to the ContactContract, I prefer not to delete all old entries and rewrite them if the did not change. I check which components changed and only update these.
The code for updating and inserting an contact to the ContactContract has been unified. There used to be two functions for these two jobs, that were to a large extend duplicates of each other (but still needed to be maintained separatly). Now there is one unified routine.
.) When turning the mobile from landscape mode to portait mode while editing a contact the changes that were already made do no longer disappear. Even the current scroll position is maintained.
.) When changing the list of shown item cateories while editing a contact, the previously made changes are not lost.
.) When selecting the ringtone "Silence" in either the view or edit activity, the corresponding field is immediatly filled correctly with "Silence", not with "Unknown Ringtone" that is replaced with Silence only on the next time the activity is redrawn.
.) Pressing the 'Back' button while editing a contact checks if any changes have been made and presents a 'Save/Discard changes?' dialog as needed.
.) In the main activity, contacts that do not have e.g. a last name (assuming sorting by last name) now get a fastscroller entry of '*' at the end of the fastscoller list, rather than some a letter based on their (e.g.) first name that may or may not pop up at the end of the fastscroller (if it is not absorbed by another entry with the same letter).
 
Note: The above changes obviuously affect both Simple-Commons and Simple-Contacts quite a lot. There are also some minor changes to Simple-Dialer and Simple-Calendar, so these need to be merged to.
Please check out:
  https://github.com/rlieger/Simple-Commons/dev_add_complete_androidcontacts
  https://github.com/rlieger/Simple-Contacts/dev_add_complete_androidcontacts
  https://github.com/rlieger/Simple-Dialer/dev_add_complete_androidcontacts
  https://github.com/rlieger/Simple-Calendar/dev_add_complete_androidcontacts

Looking forward to your comments,
  Roland

### CODE REVIEW

**Comment by tibbi** [comment]
thanks, but thats definitely how it should be done

**Comment by rlieger** [comment]
Hello,

 

Thanks for you fast response. However it is quite short and I somehow fail to understand what you are refering to.

 

>> thanks, but thats definitely how it should be done<<

 

What is this "it" and what's "that" way that seems to be the correct way to do "it"?

 

I provided many suggestions, improvements and bugfixes. Which of these seems to be wrong to you and why?

Please do not get me wrong. I fully understand that this is _your_ project and that you have all rights to decide which contributions you wish to accept and which to reject. However it would be nice if you provided some insight why a particular contribution is not welcome and/or what I should have done (or should do in the future) to gain acceptance.

 

Kiind regards,

   Roland

 

Gesendet: Dienstag, 09. Mai 2023 um 22:57 Uhr
Von: "Tibor Kaputa" ***@***.***>
An: "SimpleMobileTools/Simple-Contacts" ***@***.***>
Cc: "Roland Lieger" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [SimpleMobileTools/Simple-Contacts] Dev add complete androidcontact (PR #980)


 

thanks, but thats definitely how it should be done

**Comment by tibbi** [comment]
well, you sent changes to 90 files with lots of unrelated and simply wrong code...

**Comment by rlieger** [comment]
Yes, there were a lot of changes. Would you mind pointing out at least one sample of wrong code.

 

I tried doing a step-by-step approach first and presented just code for storing relation information hoping that I it would get accepted (or at least feedback) and I could continue working from there. Nothing happend for three weeks, so I decided to retract that pull request and go for all-in. Obviously that was not wat you wanted. Lesson learned.

 
 

Gesendet: Mittwoch, 10. Mai 2023 um 13:06 Uhr
Von: "Tibor Kaputa" ***@***.***>
An: "SimpleMobileTools/Simple-Contacts" ***@***.***>
Cc: "Roland Lieger" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [SimpleMobileTools/Simple-Contacts] Dev add complete androidcontact (PR #980)


 

well, you sent changes to 90 files with lots of unrelated and simply wrong code...

**Comment by tibbi** [comment]
theres too many issues to list them, you commented out a lot of code and write new code in a different style, not accepting the current code styling

**Pull request closed without merging**
