### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ltGuillaume**
Question!

When is `is_calling` used, and when `dialing`?

### CODE REVIEW

**Comment by tibbi** [comment]
both are used at the notification

**Comment by ltGuillaume** [comment]
But is it like "Some Name is calling..."?

**Comment by tibbi** [comment]
no, the top line says the Name, the bottom line only "Is calling...". The bottom line is always changed depending on the call status.

**Comment by ltGuillaume** [comment]
Thanks! Just changed the translation accordingly (and translated the new string).

**Comment by tibbi** [comment]
have you created a new pull request?

**Comment by tibbi** [comment]
oh in the dialer you mean

**Comment by ltGuillaume** [comment]
Ooh right, had forgotten for a moment that these strings are now present in both apps. Made a pull request.

**Comment by tibbi** [comment]
well the Contacts app will probably lose everything dialer related already in the next version released soon. Many things have been improved in the standalone Simple Dialer and I dont want to copypaste anything.

**Comment by ltGuillaume** [comment]
Makes sense. What exactly required a new app for it?

**Comment by tibbi** [comment]
Strictened rules for granting the Call Log permission by Google. Simple Contacts Pro didn't receive it even after requesting and appealing multiple times, as the Phone is not the core functionality of the app. Having a calling app without showing a call history causes a lot of bad ratings.

**Comment by ltGuillaume** [comment]
Ugh, what a drag...

**Pull request merged**
