### PR TITLE
Add an option to show/hide contact thumbnails

### PR DESCRIPTION
**Pull request by trubitsyn**

### CODE REVIEW

**Comment by trubitsyn** [comment]
The string that has already been in the app had been named "show_contact_avatars" though, should I rename it?

**Comment by tibbi** [comment]
yea, guess you can rename it. Also if the value changes I wouldnt restart the whole activity, just update the lists. At around line 194 of ContactsAdapter use the contact_tmb.beVisibleIf(showContactThumbnails) thing. Thanks

**Comment by trubitsyn** [comment]
I've left the if clause to avoid Glide invocation and save some resources.

**Comment by trubitsyn** [comment]
Could you please point me where should I update the lists? Can't get the place.

**Comment by tibbi** [comment]
ye that if (showContactThumbnails) { check is good to avoid Glide. 
You can refresh the lists at the spot where you are restarting the activity, just replace "restartActivity()" and "return" with "refreshContacts()", doesnt it work? Im restarting it at toggling phone number visibility just because Im inflating a different view in the adapter and it was glitchy.

**Comment by trubitsyn** [comment]
No, it does not work unfortunately :(

**Comment by tibbi** [comment]
aha ye, because the hashcode of the contacts is the same. Ill finish it, thanks

**Comment by tibbi** [comment]
as I see I changed some strings with the conflict resolving too, check if its ok please

**Comment by trubitsyn** [comment]
Oh, thought the hashcode stuff had already been correctly implemented there. Thanks for finishing.
It's OK, there's no difference at all between these two translations. Though "show_contact_avatars" string resource showed up again instead of "show_contact_thumbnails". I'll rename it in a new PR for consistency.

**Pull request merged**
