### PR TITLE
Add option to edit structured address

### PR DESCRIPTION
**Pull request by stephanritscher**
If "Structured Address (edit mode)" is checked in the field visibility dialog of settings, then the contact edit mode will display structured address fields (country, region, city, postcode, pobox, street, neighborhood) instead of the formatted address. The field formatted address will be set to the composite of these fields (analogous to DAVdroid).

### CODE REVIEW

**Comment by tibbi** [comment]
well thanks, but I dont really want to add it as it is the exact opposite of the main objective of the apps, which is keeping them simple. I might get back to it one day if I change my mind.

**Comment by stephanritscher** [comment]
Hi tibi,

never mind.

I use DAVdroid for syncing contacts witch Nextcloud and then sync to Thunderbird using Sogo Connector - maybe not the most common setup. If I only set the formatted address, the changes get lost somewhere on the way since Thunderbird only has the structured address fields.

I had been looking for a contact app which can edit the structured address fields, but only found Google Contacts so far (which I didn't like as much).

I thought it might be in your sense since the feature is off by default and the behaviour shouldn't be changed in this case.

On the other hand I can update and build my fork from time to time on my own - I guess I won't need as many updates for the contacts app 😉.

All the best
Stephan

**Comment by tibbi** [comment]
so far maybe 1 person asked about that structured address, I dont remember more people and I dont really like that either. Recently I enabled inserting multiple lines in the Address field, that will help some people. Indeed some services try syncing the structured one, some the simple one. I will consider it adding in the future only if a lot of people ask for it.

**Comment by Glaser-Martin** [comment]
@stephanritscher I would like to see your fork available as a separate app in F-Droid. 

I believe that many users wait for that. I can not imagine to use a contacts app that does not provide separate address fields as intended by the CardDAV standard and I also want to continue managing my contacts in Nextcloud. 

For the aim I created already https://gitlab.com/fdroid/rfp/-/issues/2241.

To make it happen, it will be necessary to make a few further changes to the fork that make the fork an own app (name, icon, identification). I could help with that. 

What is your opinion? In which way do you want to go forward? Can we work together?

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin,

First of all sorry for the late response.

I'm glad to hear it isn't only me who has this problem 😉.

**Comment by Glaser-Martin** [comment]
Hello @stephanritscher,

with my time budget it is similar as with yours. There is little. But I think it can not be that much work to make the fork a separate app and bring it into F-Droid. So step by step I will bring this forward.

I am just beginning with GitHub, GitLab, git, Android programming, Kotlin and F-Droid. I have some programming experience, also with Java, so I can read and understand things and then modify. I think for modifying an icon and some descriptive information about an app it should be fine. I might make stupid errors though and also might need some increments to get things right. A problem is that I have no means to create an APK myself, I tried but failed. So test will mean F-Droid. Also the simple use of git to get something changed in a GitHub repo and to update the repo with changes from upstream is something I need to learn first. If I could get guidance it would be easier for sure.

tibbi has the original Simple Contacts already on F-Droid and so in general it should be suitable for it without bigger rework. I think your modifications will not make a differrence to that.

I wonder if the right way is to make another fork on top of your fork that will get the changes to make the app separate? Then you still have the possibility to build your fork with the original name and also tibbi still has it easy to incooperate the functional change back to the original in case he reconsiders.

Or would you prefer to directly change your fork?

Will a fork of a fork work at all with GitHub?

Do you know in which files the applicationId and the app name are defined/contained?

I am not so sure about changing the icon. There are many files with different sizes and colors in the repo (ic_launcher*.png I guess are the files). And the icon is also in the screenshot files under fastlane folder.

I would sell the fork in F-Droid anyhow as fork of Simple Contacts with one important difference. So for what a distinct icon?

Let me know your thoughts.

Best Regards

 Martin

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin,

I invited you as collaborator to my fork. I hope we can work together more easily this way.
Separating the feature change and the app id stuff is a good idea. I would propose to work with branches. I can explain details later, but basically there will be one branch A with original app + structured address feature and one branch B with original app + structured address feature + changes we need for publishing as separate app in fdroid. When we do updates the merge chain will be SimpleMobileTools/Simple-Contacts:master => A => B. We still can decide if stephanritscher/Simple-Contacts:master is A or B (maybe relevant for F-Droid?).
I will try to check why the build isn't working anymore...

All the best,
Stephan

**Comment by stephanritscher** [comment]
Regarding the build, I had a lot of errors downloading dependencies in the "Configure project app:" phase (`Read timed out`), but was able to resolve them by running `./gradlew build` _many_ times (the packages that could not be downloaded varied mostly from run to run, rarely they repeated a couple of times). It seems to me that the repositories were/are overloaded or my internet connection very crappy. I must say I never experienced this before.

But finally, the build was successful. If you have different kinds of errors, let please post them so I could have a look.

Updating the fork is more difficult than I thought since SimpleMobileTools/SimpleContacts and SimpleMobileTools/SimpleCommons seem to be out of sync with the former not being updated for a month and the latter having tons of very recent commits. I'd rather wait for the situation to settle upstream than spend more time trying to fix it myself.

**Comment by Glaser-Martin** [comment]
Hi @stephanritscher,

branches as suggested are fine I think. 

F-Droid seems to work with git on the master, so stephanritscher/Simple-Contacts:master would better be B.

Here is the documentation that I checked:

https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

https://f-droid.org/en/docs/Build_Metadata_Reference/

For the upstream version following metadata file is used:

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.simplemobiletools.contacts.pro.yml

A link to that file can be found under "Build Metadata" on https://f-droid.org/en/packages/com.simplemobiletools.contacts.pro/.

AutoUpdateMode and UpdateCheckMode are set up so that whenever tibbi adds a new tag containing a higher version than the previous, F-Droid creates and publishes a new version.

We can use the same approach.

Your latest sync with upstream was with upstream version 6.19.1. If we overtake that version and amend it with an additional counter and create then the tags (for example 6.19.1.1), we clearly document on which upstream version our release is based and have the possibility to make multiple releases per upstream release if we need.

Regarding the build: I tried to build on a Debian cloud server following a recipe that I found on https://wiki.debian.org/AndroidTools/IntroBuildingApps. First with `gradle build --init-script /usr/share/android-sdk-helper/init.gradle` (it failed with an error about wrong gradle version) and then with `gradlew` and `gradlew assembleFdroid` which failed (as far as I can remember), because gradle complained that a child process of gradle disappeared (I guess it crashed). Not sure if I can be successful with such a wild approach. I am not willing to install on my own machine a full Android development environment including Android Studio. Do not waste time on that with me.

Don't worry about updating the fork, I think for now we can fine work with the version that is there.

I checked through the repository to find the places that need updating and found:

- `app/build.gradle` defines `applicationId`
- `app/src/main/res/values/strings.xml` defines `app_name`, `app_launcher_name`, `app_short_description` and `app_long_description`. But this file is localized in `app/src/main/res/values-*`. I guess I have to change `app_name` there in order to get a different app name on the F-Droid app page, but all other is not used by F-Droid (also not the localized versions of `app_name`), so I would change only `app_name` and only in `app/src/main/res/values/strings.xml`.
- `fastlane/metadata/android/en-US/full_description.txt`, `short_description.txt` and `title.txt` are used by F-Droid, so I would update these, but also only in the en-US version, the other languages I would just delete
- Maybe I would change `README.md` with content similar to `full_description.txt`, `short_description.txt` to have also a good README on GitHub.

And that is it then I think. Then I would start a new go on F-Droid side.

Best Regards

 Martin

**Comment by stephanritscher** [comment]
Hi @Glaser-Martin,

regarding the build: my fork contained a commit increasing the heap size to 16 GB to speed up the process on my 32 GB machine. This might cause an OutOfMemoryError or similar if the machine has less memory. I removed this change so you can retry the build.
Regarding branches: structured-address is branch A in above sense, master now contains a draft of your suggested changes.
I also created a tag 6.19.1.1 as suggested.

Best regards,
Stephan

**Comment by Glaser-Martin** [comment]
Hi @stephanritscher,

thank you very much. The draft looks good to me.

I see that now there are many new tags added besides 6.19.1.1, problematic I think are 6.20.0, 6.21.0 and 6.21.1, because these are higher than 6.19.1.1 and F-Droid probably picks then 6.21.1. Can you remove these 3, please?

I created attached [de.ritscher.simplemobiletools.contacts.pro.yml.zip](https://github.com/SimpleMobileTools/Simple-Contacts/files/9995419/de.ritscher.simplemobiletools.contacts.pro.yml.zip) as a suggestion for the metadata file (zip, because GitHub does not accept yml as attachment). I intend to provide that to the F-Droid request. Please check if the content is fine with you.

Best Regards

 Martin

**Comment by Glaser-Martin** [comment]
Ups, what happened here, where are all the comments from @stephanritscher and me?

@tibbi have you deleted them?

As you probably have seen, we intend to provide a variant of Simple Contacts on F-Droid that will have the option for structured addresses as described in this Pull Request.

I am just about to prepare the metadata file for F-Droid and I ask myself what shall happen with AuthorName, AuthorEmail, WebSite, IssueTracker, Donate/Bitcoin/Litecoin? My original plan was to keep that as it is as certainly the variant is still mostly your work.

Is that allright for you? Or shall I better remove/replace that information?

**Comment by tibbi** [comment]
discuss it somewhere else, this isnt slack

**Pull request closed without merging**
