### PR TITLE
Fix phone category

### LINKED ISSUE #925: "Main" telephone type is not correctly exported/imported
**Environment:**
Android 13
OxygenOS 13.0 (OnePlus 10 Pro 5G)
Simple Contact Pro v6.22.0

**Steps to reproduce:**
- Create a new test contact and enter a phone number of type "Main"
- Export that contact using the share function, it will be exported as a vcf
- Delete the test contact
- Import the vcf

**Actual result:**
- The phone number type field is empty

**Expected result:**
- The phone number type field should say "Main", as previously selected

**Possible reason for this behaviour:**
When looking at the exported vcf, the culprit line says
`TEL;PREF=1:+123456789`
Whereas a phone number with type "Work" would yield
`TEL;TYPE=WORK:+12345555678`

So I tried substituting "PREF=1" with "TYPE=MAIN". **And this actually worked.** Importing it after that change yields "Main" in the type field. So either changing the importing or the exporting will fix this issue.

### PR DESCRIPTION
**Pull request by Mylloon**
Hello,

This PR fixes #925.

Co-authored-by: @Pachat2000

### CODE REVIEW

**Comment by tibbi** [comment]
nice, thanks

**Comment by tibbi** [comment]
how about importing? This line seems suspicious in that regard aswell https://github.com/SimpleMobileTools/Simple-Contacts/blob/514a39f125fb0b07215c22ac45dd0ed5d9fa0582/app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfImporter.kt#L270

**Comment by Mylloon** [comment]
Yes, currently PREF is not well exported either

**Comment by tibbi** [comment]
so you will take a look at it, or there is nothing to change? I havent tested it properly yet

**Comment by Mylloon** [comment]
I can take a look

**Comment by Mylloon** [comment]
After some research I believe I got confused, the star is represented by `is_primary`.

**Pull request merged**
